### ISSUE TITLE
Homekit Automations Failing

### ISSUE THREAD

**Issue by ponkeydunch** [d0n4v4nb3ck3r/homebridge-honeywell-home#523]
Homekit commands I issue (manually changing the temperature) are working. However, timed automations are not functioning and returning an error code.

Specific Logs:

[02/08/2021, 12:00:01] [HoneywellHome] "Request failed with status code 400"
(node:894) UnhandledPromiseRejectionWarning: Error: HAP Status Error: -70408
    at new HapStatusError (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/hapStatusError.ts:15:5)
    at Thermostats.apiError (/usr/local/lib/node_modules/homebridge-honeywell-home/src/devices/thermostats.ts:634:11)
    at /usr/local/lib/node_modules/homebridge-honeywell-home/src/devices/thermostats.ts:261:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:894) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:894) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Config:

{
    "bridge": {
        "name": "Homebridge ****",
        "username": "0E:73:7E:31:**:**",
        "port": 516**,
        "pin": "***-**-***"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "devices": [
                {
                    "ipAddress": "10.***.1.**",
                    "serialNumber": "VV6-US-*******",
                    "credentials": "eyJTZXJpYWwiOiJWVjYtVVMtS0ZBMTgxMUEiLCJOYW1lIjoiTWFzd**************uIjoiRUNHMlBGLjAyLjA2LjAwMy4wMDAyIiwiTG9jYWxDcmVkZW50aWFscyI6IjRQVk9sbG1iUGdzWExBRzdHSHB4dytPMnZscHBrVzc4U1d5UnByOW53WGsveEprQURnTTBtMlE0aHBSMVRrY2duaWVtRm1OWmdCME4xWFJhdEQ5Ty9MQnJ2bHNVNkYvL2hvd2NJV0F5NktuajdTaVFoNXBRZTBQd0ZGMkw5Rmc5cXpMNU1DNjNCbXZGa2ZVaSs2aTNFdUVsbU5HNS**********mY3R0hFNncxYWx2eEFsRGVtalQyaSIsIkF1dG9VcGRhdGUiOnRydWUsIk5ld1ZlcnNpb25BdmFpbGFibGUiOmZhbHNlLCJQcm9kdWN0VHlwZSI6IjUyMCIsIkNvbm5lY3Rpb25UeXBlIjoid3NzIiwicGFzc3dvcmQiOiJsMjFqT1pYQWVMMDJGaFhIakZQTTROOEpSaWJRbDhDdit0aldtUmlaYUhrUVJwOW02clhaaGQ2UEpJYUk4ZkwrNENVZHpmcHgrd0JTRkNmNHRqU0Rqdz09In0=",
                    "enableAutoModeWhenActivating": true,
                    "enableOscillationWhenActivating": true,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isContinuousMonitoringEnabled": false,
                    "isTemperatureSensorEnabled": false,
                    "isHumiditySensorEnabled": false,
                    "isAirQualitySensorEnabled": false,
                    "isSingleSensorAccessoryModeEnabled": false,
                    "isSingleAccessoryModeEnabled": false,
                    "isFullRangeHumidity": false,
                    "isHeatingDisabled": false
                }
            ],
            "platform": "DysonPureCoolPlatform"
        },
        {
            "name": "Rachio",
            "api_key": "********-b085-43c4-****-cd5f25624fc7",
            "external_webhook_address": "http://104.***.178.44:***",
            "internal_webhook_port": 808,
            "clear_previous_webhooks": true,
            "platform": "Rachio-Platform"
        },
        {
            "name": "HoneywellHome",
            "options": {
                "refreshRate": 300,
                "thermostat": {
                    "thermostatSetpointStatus": "PermanentHold"
                },
                "roompriority": {
                    "priorityType": "PickARoom"
                }
            },
            "platform": "HoneywellHome",
            "credentials": {
                "consumerKey": "urhvPtSeCA*******f5aFgKGyYOoT",
                "consumerSecret": "Dxj0*****Q8ip**nYe",
                "accessToken": "10dyY1MCx*******gvVG8uUBihMp",
                "refreshToken": "BXNZn1TP6lmZ9yA*******Ig0Y9q"
            }
        }
    ]
}

Model: Lyric T6

# **Environment:**

- **Node.js Version**: v14.17.4
- **NPM Version**: 6.14.14
- **Homebridge Version**: 1.3.4
- **Homebridge Honeywell Home Plugin Version**: 9.6.0
- **Homebridge Config UI X Plugin Version**: 4.41.2
- **Operating System**: Homebridge running on Pi

**Comment by ponkeydunch** [comment]
I looked through some old issues and saw that someone fixed a similar error by deleting the cache. I deleted mine and now the automations seem to be working without spitting back error codes. 

Feel free to close this.

Thank you for the app!
