### ISSUE TITLE
Bug: TypeError crashes Homebridge

### ISSUE THREAD

**Issue by tbaur** [d0n4v4nb3ck3r/homebridge-honeywell-home#786]
### Describe The Bug

TypeError crashes Homebridge

### To Reproduce

TypeError crashes Homebridge

### Expected behavior

Does not crash Homebridge

### Relevant log output

```shell
[7/4/2023, 11:53:55 AM] TypeError: Cannot read properties of undefined (reading 'temperature')
    at LeakSensor.parseStatus (/usr/local/lib/node_modules/homebridge-resideo/src/devices/leaksensors.ts:178:67)
    at new LeakSensor (/usr/local/lib/node_modules/homebridge-resideo/src/devices/leaksensors.ts:80:10)
    at ResideoPlatform.Leak (/usr/local/lib/node_modules/homebridge-resideo/src/platform.ts:579:9)
    at ResideoPlatform.deviceClass (/usr/local/lib/node_modules/homebridge-resideo/src/platform.ts:430:14)
    at ResideoPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-resideo/src/platform.ts:401:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/4/2023, 11:53:55 AM] Got SIGTERM, shutting down Homebridge...
```

### Config for homebridge-resideo

```shell
N/A
```

### Device & Model

N/A

### Node.js Version

Current

### NPM Version

Current

### Homebridge Version

Current

### Homebridge Resideo Plugin Version

Current

### Homebridge Config UI X Plugin Version

Current

### Operating System

OSX

**Comment by donavanbecker** [comment]
@tbaur Can you try disabling temperature using the config to bypass till I have time to fix this.

**Comment by donavanbecker** [comment]
v1.4.0 has been released which should resolve this.
