### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by holmesca08** [d0n4v4nb3ck3r/homebridge-honeywell-home#816]
### Describe Your Problem

No Link Account button or refresh token

### Relevant log output

```shell
2/4/2024, 12:39:54 PMResideo BridgeERRORError loading plugin "homebridge-resideo"
2/4/2024, 12:39:54 PMResideo BridgeERRORReadableStream is not defined
2/4/2024, 12:39:54 PMResideo BridgeERRORReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/var/lib/hoobs/resideobridge/node_modules/undici/lib/fetch/response.js:507:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/resideobridge/node_modules/undici/lib/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/resideobridge/node_modules/undici/index.js:97:19)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
2/4/2024, 12:39:54 PMResideo BridgeWARNINGNo plugins installed.
2/4/2024, 12:39:54 PMResideo BridgeLoading 1 platforms...
2/4/2024, 12:39:54 PMResideo BridgeBridge is running on port 51856.
2/4/2024, 12:39:54 PMResideo BridgeWARNINGunhandled rejection: ReferenceError: ReadableStream is not defined
2/4/2024, 12:40:00 PMArlo Bridge starting
2/4/2024, 12:40:03 PMRainbird BridgeERRORRainBird controller request failed. [Error: connect EHOSTUNREACH 192.168.50.55:80]
2/4/2024, 12:40:03 PMRainbird BridgeERRORFailed Request: [2] [ModelAndVersionRequest]
2/4/2024, 12:40:03 PMRainbird BridgeERRORWill retry in 60 seconds
2/4/2024, 12:40:16 PMArlo Bridge starting
2/4/2024, 12:40:26 PMResideo BridgeConfiguration change
2/4/2024, 12:40:26 PMresideobridge stopping
2/4/2024, 12:40:31 PMResideo Bridge starting
2/4/2024, 12:40:31 PMArlo Bridge starting
2/4/2024, 12:40:31 PMResideo Bridge starting
2/4/2024, 12:40:31 PMArlo Bridge starting
2/4/2024, 12:40:42 PMResideo BridgeERRORError loading plugin "homebridge-resideo"
2/4/2024, 12:40:42 PMResideo BridgeERRORReadableStream is not defined
2/4/2024, 12:40:42 PMResideo BridgeERRORReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/var/lib/hoobs/resideobridge/node_modules/undici/lib/fetch/response.js:507:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/resideobridge/node_modules/undici/lib/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/resideobridge/node_modules/undici/index.js:97:19)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
2/4/2024, 12:40:42 PMResideo BridgeWARNINGNo plugins installed.
2/4/2024, 12:40:42 PMResideo BridgeLoading 1 platforms...
2/4/2024, 12:40:42 PMResideo BridgeBridge is running on port 51856.
2/4/2024, 12:40:42 PMResideo BridgeWARNINGunhandled rejection: ReferenceError: ReadableStream is not defined
```

### Config for homebridge-resideo

```shell
Using hoobs so not sure how to access json
```

### Screenshots

[Resideo HomeBridge Screenshots.docx](https://github.com/donavanbecker/homebridge-resideo/files/14157722/Resideo.HomeBridge.Screenshots.docx)

### Device & Model

Hoobs Starter Box

### Node.js Version

N/A

### NPM Version

N/A

### Homebridge Version

4.3.1

### Homebridge Resideo Plugin Version

2.0.0

### Operating System

Hoobs

**Comment by donavanbecker** [comment]
This plugin isn't developed for HOOBs.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

**Comment by holmesca08** [comment]
Hi Donavan,I am reviewing the Official Homebridge Raspberry Pi Image, does it matter if I buy a Raspberry Pi 4 B or a regular Raspberry Pi 4? Also seeing if I can return the HOOBs. Cam HolmesPhone: (540) ***@***.*** Feb 4, 2024, at 3:46 PM, Donavan Becker ***@***.***> wrote:﻿
This plugin isn't developed for HOOBs.
I would recommend moving to homebridge.

**Comment by donavanbecker** [comment]
Nope either one of them should work. You can also reflash your HOOBs box but it would be cheaper to return and get a pi4.

**Comment by holmesca08** [comment]
Thanks for that info. Out of curiosity, why won’t the Resideo plugin work with Hoobs?On Feb 7, 2024, at 6:25 AM, Donavan Becker ***@***.***> wrote:﻿
Nope either one of them should work. You can also reflash your HOOBs box but it would be cheaper to return and get a pi4.

**Comment by donavanbecker** [comment]
@holmesca08 Because i didn't design it too, and also to get the refresh token, the Homebridge UI had a way built in to handle that.
