### ISSUE TITLE
Bug: Changing log level crashes Homebridge

### ISSUE THREAD

**Issue by dangitall** [d0n4v4nb3ck3r/homebridge-honeywell-home#832]
### Describe The Bug

Changing the log level in the Plugin ConfigUI to "Standard" or "Debug" puts Homebridge in a restart loop

### To Reproduce

Via the Homebridge web UI, choose Plugins->Resideo->Plugin Config->Settings->Advanced Settings->Log Setting, change it to Debug and restart homebridge

### Expected behavior

I get more logs and homebridge runs fine.

### Relevant log output

```shell
[7/5/2024, 12:10:08 PM] Homebridge v1.8.3 (HAP v0.12.2) (Homebridge 31D9) is running on port 51235.
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] Plugin Version: 2.1.3-beta.0
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] Got access token: ozgrRkjxa5moYbnvO8jydXwlg4R2
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] accessToken: ozgrRkjxa5moYbnvO8jydXwlg4R2
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] accessToken: ozgrRkjxa5moYbnvO8jydXwlg4R2, consumerKey: vr4JiGYUei4SKzXY5MGhGG7JMFhWUYzO
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] (discoverlocations) Location: [{"locationID":5329882,"name":"Home","streetAddress":"---","city":"---","state":"---","country":"---","zipcode":"---","devices":[{"waterPresent":false,"currentSensorReadings":{"time":"2024-07-05T17:25:43","temperature":24.7,"humidity":55.6},"currentAlarms":[],"lastCheckin":"2024-07-05T17:25:51","lastDeviceSettingUpdatedOn":"2024-07-05T17:25:51","batteryRemaining":100,"isRegistered":true,"hasDeviceCheckedIn":true,"isDeviceOffline":false,"deviceOfflineTime":"2024-07-07T05:25:51","firstFailedAttemptTime":"0001-01-01T00:00:00","failedConnectionAttempts":0,"wifiSignalStrength":0,"time":"2024-07-05T17:25:51","deviceClass":"LeakDetector","deviceType":"Water Leak Detector","deviceID":"14f91d95-9889-4cd7-94d4-dcdb566c58a0","deviceInternalID":6443134,"userDefinedDeviceName":"Refrigerator","backend":{},"isAlive":true,"isUpgrading":false,"isProvisioned":true,"deviceSettings":{"temp":{"high":{"limit":37},"low":{"limit":7}},"humidity":{"high":{"limit":70},"low":{"limit":20}},"userDefinedName":"Refrigerator","buzzerMuted":false,"checkinPeriod":12,"currentSensorReadPeriod":60},"service":{"mode":"Up"},"deviceRegistrationDate":"2024-07-05T17:24:56.7066667","deviceVariant":"L1_SmartWaterSensor_Retail"},{"waterPresent":false,"currentSensorReadings":{"time":"2024-07-05T17:30:08","temperature":23.55,"humidity":53.3},"currentAlarms":[],"lastCheckin":"2024-07-05T17:30:16","lastDeviceSettingUpdatedOn":"2024-07-05T17:30:16","batteryRemaining":100,"isRegistered":true,"hasDeviceCheckedIn":true,"isDeviceOffline":false,"deviceOfflineTime":"2024-07-07T05:30:16","firstFailedAttemptTime":"0001-01-01T00:00:00","failedConnectionAttempts":0,"wifiSignalStrength":0,"time":"2024-07-05T17:30:16","deviceClass":"LeakDetector","deviceType":"Water Leak Detector","deviceID":"330a0774-05b6-42fe-a61d-e589929cc0af","deviceInternalID":6443164,"userDefinedDeviceName":"Laundry Room","backend":{},"isAlive":true,"isUpgrading":false,"isProvisioned":true,"deviceSettings":{"temp":{"high":{"limit":37},"low":{"limit":7}},"humidity":{"high":{"limit":70},"low":{"limit":20}},"userDefinedName":"Laundry Room","buzzerMuted":false,"checkinPeriod":12,"currentSensorReadPeriod":60},"service":{"mode":"Up"},"deviceRegistrationDate":"2024-07-05T17:29:28.0166667","deviceVariant":"L1_SmartWaterSensor_Retail"},{"waterPresent":false,"currentSensorReadings":{"time":"2024-07-05T17:40:47","temperature":24.58,"humidity":55.7},"currentAlarms":[],"lastCheckin":"2024-07-05T17:40:55","lastDeviceSettingUpdatedOn":"2024-07-05T17:40:55","batteryRemaining":100,"isRegistered":true,"hasDeviceCheckedIn":true,"isDeviceOffline":false,"deviceOfflineTime":"2024-07-07T05:40:55","firstFailedAttemptTime":"0001-01-01T00:00:00","failedConnectionAttempts":0,"wifiSignalStrength":0,"time":"2024-07-05T17:40:55","deviceClass":"LeakDetector","deviceType":"Water Leak Detector","deviceID":"ed469c8c-fde8-4c3e-9430-9444a1683891","deviceInternalID":6443208,"userDefinedDeviceName":"Water Heater","backend":{},"isAlive":true,"isUpgrading":false,"isProvisioned":true,"deviceSettings":{"temp":{"high":{"limit":37},"low":{"limit":7}},"humidity":{"high":{"limit":70},"low":{"limit":20}},"userDefinedName":"Water Heater","buzzerMuted":false,"checkinPeriod":12,"currentSensorReadPeriod":60},"service":{"mode":"Up"},"deviceRegistrationDate":"2024-07-05T17:39:53.0566667","deviceVariant":"L1_SmartWaterSensor_Retail"}],"users":[{"userID":6478820,"username":"---","firstname":"---","lastname":"---","created":1720200098,"deleted":-62135596800,"activated":true,"connectedHomeAccountExists":true,"locationRoleMapping":[{"locationID":5329882,"role":"Adult","locationName":"Home","status":1}],"isOptOut":"False","isCurrentUser":true}],"timeZoneId":"Pacific","timeZone":"Pacific Standard Time","ianaTimeZone":"America/Los_Angeles","daylightSavingTimeEnabled":true,"geoFenceEnabled":false,"predictiveAIREnabled":false,"comfortLevel":0,"geoFenceNotificationEnabled":false,"geoFenceNotificationTypeId":13,"configuration":{"faceRecognition":{"enabled":false,"maxPersons":2,"maxEtas":2,"maxEtaPersons":1,"schedules":[{"time":[{"start":"15:00:00","end":"17:00:00"}],"days":["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]}]}},"stateName":"California"}]
[7/5/2024, 12:10:08 PM] [Resideo] Total Locations Found: 1
[7/5/2024, 12:10:08 PM] [Resideo] Total Devices Found at Home: 3
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] Location ID: 5329882
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] No Resideo Device Config: undefined
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] Discovered Refrigerator LeakDetector @ Home
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] Device: Refrigerator hide_roomsensor: undefined, roompriority: undefined, hide_device: undefined
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] Device: Refrigerator deviceID: 14f91d95-9889-4cd7-94d4-dcdb566c58a0, registerDevice: true
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] Device: Refrigerator will display in HomeKit
[7/5/2024, 12:10:08 PM] [Resideo] Restoring existing accessory from cache: Refrigerator DeviceID: 14f91d95-9889-4cd7-94d4-dcdb566c58a0
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] Discovered Laundry Room LeakDetector @ Home
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] Device: Laundry Room hide_roomsensor: undefined, roompriority: undefined, hide_device: undefined
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] Device: Laundry Room deviceID: 330a0774-05b6-42fe-a61d-e589929cc0af, registerDevice: true
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] Device: Laundry Room will display in HomeKit
[7/5/2024, 12:10:08 PM] [Resideo] Restoring existing accessory from cache: Laundry Room DeviceID: 330a0774-05b6-42fe-a61d-e589929cc0af
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] Discovered Water Heater LeakDetector @ Home
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] Device: Water Heater hide_roomsensor: undefined, roompriority: undefined, hide_device: undefined
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] Device: Water Heater deviceID: ed469c8c-fde8-4c3e-9430-9444a1683891, registerDevice: true
[7/5/2024, 12:10:08 PM] [Resideo] [DEBUG] Device: Water Heater will display in HomeKit
[7/5/2024, 12:10:08 PM] [Resideo] Restoring existing accessory from cache: Water Heater DeviceID: ed469c8c-fde8-4c3e-9430-9444a1683891
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugWarnLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:320:14)
    at LeakSensor.getDeviceLogSettings (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:61:12)
    at new deviceBase (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:36:10)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:59:5)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:342:14)
    at LeakSensor.getDeviceRateSettings (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:81:12)
    at new deviceBase (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:37:10)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:59:5)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:342:14)
    at LeakSensor.getDeviceRetry (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:107:12)
    at new deviceBase (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:38:10)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:59:5)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugSuccessLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:306:14)
    at LeakSensor.getDeviceConfigSettings (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:157:12)
    at new deviceBase (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:39:10)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:59:5)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugSuccessLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:306:14)
    at LeakSensor.getDeviceContext (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:189:12)
    at new deviceBase (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:40:10)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:59:5)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:342:14)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:94:12)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugWarnLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:320:14)
    at LeakSensor.getDeviceLogSettings (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:61:12)
    at new deviceBase (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:36:10)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:59:5)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:342:14)
    at LeakSensor.getDeviceRateSettings (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:81:12)
    at new deviceBase (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:37:10)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:59:5)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:342:14)
    at LeakSensor.getDeviceRetry (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:107:12)
    at new deviceBase (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:38:10)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:59:5)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugSuccessLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:306:14)
    at LeakSensor.getDeviceConfigSettings (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:157:12)
    at new deviceBase (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:39:10)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:59:5)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugSuccessLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:306:14)
    at LeakSensor.getDeviceContext (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:189:12)
    at new deviceBase (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:40:10)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:59:5)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:342:14)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:94:12)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugWarnLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:320:14)
    at LeakSensor.getDeviceLogSettings (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:61:12)
    at new deviceBase (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:36:10)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:59:5)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:342:14)
    at LeakSensor.getDeviceRateSettings (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:81:12)
    at new deviceBase (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:37:10)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:59:5)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:342:14)
    at LeakSensor.getDeviceRetry (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:107:12)
    at new deviceBase (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:38:10)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:59:5)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugSuccessLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:306:14)
    at LeakSensor.getDeviceConfigSettings (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:157:12)
    at new deviceBase (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:39:10)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:59:5)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugSuccessLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:306:14)
    at LeakSensor.getDeviceContext (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:189:12)
    at new deviceBase (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:40:10)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:59:5)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] TypeError: Cannot read properties of undefined (reading 'includes')
    at LeakSensor.enablingDeviceLogging (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:352:31)
    at LeakSensor.debugLog (file:///homebridge/node_modules/homebridge-resideo/src/devices/device.ts:342:14)
    at new LeakSensor (file:///homebridge/node_modules/homebridge-resideo/src/devices/leaksensors.ts:94:12)
    at ResideoPlatform.createLeak (file:///homebridge/node_modules/homebridge-resideo/src/platform.ts:649:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/5/2024, 12:10:09 PM] Got SIGTERM, shutting down Homebridge...
```

### Config for homebridge-resideo

```shell
{
    "name": "Resideo",
    "credentials": {
        "consumerKey": "---",
        "consumerSecret": "---",
        "refreshToken": "---",
        "notice": "Keep your tokens a secret!"
    },
    "platform": "Resideo"
}
```

### Device & Model

L1 Leak detector, hw 2.1.2, fw 2.1.2

### Node.js Version

v20.12.2

### NPM Version

v10.5.0

### Homebridge Version

1.8.3

### Homebridge Resideo Plugin Version

v2.1.2 & v2.1.3-beta

### Homebridge Config UI X Plugin Version

v4.56.4

### Operating System

Docker

**Comment by donavanbecker** [comment]
I am not able to reproduce

**Comment by dangitall** [comment]
Well, I just tried again with v2.1.3 and it works fine.
